description: Começar com dados na AWS através de templates e plugins prontos feitos em Terraform
name: data-analytics
display-name: data-analytics
picture: stack.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility: # Put a list of technologies compatible with the stack
  - java
  - spring
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies 
  - docker 
about: docs/about.md
use-cases:
  - title: Stack básica para começar com dados na AWS utilizando S3, Glue e Athena
    content: docs/use-case.md
    stackfile: stackfiles/default.yaml